# .readthedocs.yaml

version: 2

sphinx:
  configuration: src/docs/conf.py


formats:
  - pdf
  - epub

python:
  version: 3.12
  install:
    - requirements: requirements.txt
    - path: .


build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

image: latest

submodules:
  include:
    - "*"
  recursive: true


requirements_file: requirements.txt

pip_install:
  - . 
