# .readthedocs.yaml

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: src/docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

python:
  version: 3.12
  install:
    - requirements: requirements.txt
    - path: .

# Build environments
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Use the default image for building docs
image: latest

# Set the subdirectory for source files
submodules:
  include: true
  recursive: true

# Set the requirements file for pip
requirements_file: requirements.txt

# Set the pip install options for building the docs
pip_install:
  - .  # This will install your package in the current directory
